### ISSUE TITLE
I have a problem when I start the exe.

### ISSUE THREAD

**Issue by skyBing** [Silvris/MDF-Manager#2]
When I start the mdf-manager.exe，it tells me that I need to install .Net. I can't open the exe. Can you tell me what the .Net website it is？

**Comment by MinoumimiSenpai** [comment]
well well... 🤣😖
ive had this issue literally since Rise launched 🤬
basically had been 100% C***Blocked by mdf files from doing any actual mesh editing..
And well..
After installing pretty much every single .net versions in history..
Still.. Nothing was working
But i just got it to work  🎻..
And well..
the fix is so simple it makes me want to puke 🤮🤣

### **EDIT**
_Turns out it Actually might be better to just install 5.0 instead/before 6.0_
• [.NET Desktop Runtime 5.0](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-5.0.0-windows-x64-installer)
• [ASP.NET Core Runtime 5.0](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-5.0.0-windows-x64-installer)

or Here is the .net download [Archives](https://dotnet.microsoft.com/en-us/download)

**Comment by skyBing** [comment]
It works. Thank you.

**Comment by Silvris** [comment]
For future reference, MDF Manager currently runs off of .NET 5.0, and thus needs the corresponding runtime.
